FROM golang:1.26.5-alpine AS build

WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 go build -trimpath -ldflags='-s -w' -o /platform .

FROM gcr.io/distroless/static-debian12:nonroot

# Default PostgreSQL connection shared by every service.
# POSTGRES_USER, POSTGRES_PASSWORD and POSTGRES_DATABASE are injected at runtime.
ENV POSTGRES_HOST=localhost \
    POSTGRES_PORT=5432 \
    POSTGRES_USER= \
    POSTGRES_PASSWORD= \
    POSTGRES_DATABASE=

# Default SQL and cache settings shared by every service.
# Individual <SERVICE>_* values override the corresponding SERVICES_* value.
ENV SERVICES_MAX_CONNECTIONS=0 \
    SERVICES_QUERY_TIMEOUT=0s \
    SERVICES_CACHE_L1_DELAY=0s \
    SERVICES_CACHE_L2_DELAY=0s \
    SERVICES_CACHE_ENABLED=false \
    SERVICES_CACHE_SIZE=0 \
    SERVICES_CACHE_TTL_CHECK=0s

# Control service PostgreSQL, cache and encrypted-secret settings.
# CONTROL_* overrides global POSTGRES_* and SERVICES_* settings.
ENV CONTROL_POSTGRES_HOST= \
    CONTROL_POSTGRES_PORT=0 \
    CONTROL_POSTGRES_USER= \
    CONTROL_POSTGRES_PASSWORD= \
    CONTROL_POSTGRES_DATABASE= \
    CONTROL_MAX_CONNECTIONS=0 \
    CONTROL_QUERY_TIMEOUT=0s \
    CONTROL_CACHE_L1_DELAY=0s \
    CONTROL_CACHE_L2_DELAY=0s \
    CONTROL_CACHE_ENABLED=false \
    CONTROL_CACHE_SIZE=0 \
    CONTROL_CACHE_TTL_CHECK=0s \
    CONTROL_SECRET_ENCRYPTION_KEY=

# Calendar service PostgreSQL and cache settings.
# CALENDAR_* overrides global POSTGRES_* and SERVICES_* settings.
ENV CALENDAR_POSTGRES_HOST= \
    CALENDAR_POSTGRES_PORT=0 \
    CALENDAR_POSTGRES_USER= \
    CALENDAR_POSTGRES_PASSWORD= \
    CALENDAR_POSTGRES_DATABASE= \
    CALENDAR_MAX_CONNECTIONS=0 \
    CALENDAR_QUERY_TIMEOUT=0s \
    CALENDAR_CACHE_L1_DELAY=0s \
    CALENDAR_CACHE_L2_DELAY=0s \
    CALENDAR_CACHE_ENABLED=false \
    CALENDAR_CACHE_SIZE=0 \
    CALENDAR_CACHE_TTL_CHECK=0s

# CPA service PostgreSQL and cache settings.
# CPA_* overrides global POSTGRES_* and SERVICES_* settings.
ENV CPA_POSTGRES_HOST= \
    CPA_POSTGRES_PORT=0 \
    CPA_POSTGRES_USER= \
    CPA_POSTGRES_PASSWORD= \
    CPA_POSTGRES_DATABASE= \
    CPA_MAX_CONNECTIONS=0 \
    CPA_QUERY_TIMEOUT=0s \
    CPA_CACHE_L1_DELAY=0s \
    CPA_CACHE_L2_DELAY=0s \
    CPA_CACHE_ENABLED=false \
    CPA_CACHE_SIZE=0 \
    CPA_CACHE_TTL_CHECK=0s

# Payment service PostgreSQL, cache and background worker settings.
# PAYMENT_* overrides global POSTGRES_* and SERVICES_* settings.
ENV PAYMENT_POSTGRES_HOST= \
    PAYMENT_POSTGRES_PORT=0 \
    PAYMENT_POSTGRES_USER= \
    PAYMENT_POSTGRES_PASSWORD= \
    PAYMENT_POSTGRES_DATABASE= \
    PAYMENT_MAX_CONNECTIONS=0 \
    PAYMENT_QUERY_TIMEOUT=0s \
    PAYMENT_CACHE_L1_DELAY=0s \
    PAYMENT_CACHE_L2_DELAY=0s \
    PAYMENT_CACHE_ENABLED=false \
    PAYMENT_CACHE_SIZE=0 \
    PAYMENT_CACHE_TTL_CHECK=0s \
    PAYMENT_PRICE_UPDATE_INTERVAL=0s \
    PAYMENT_PRICE_UPDATE_BASE_URL= \
    PAYMENT_DISABLE_PRICE_UPDATER=false \
    PAYMENT_ORDER_EXPIRATION_INTERVAL=0s \
    PAYMENT_ORDER_EXPIRATION_AGE=0s \
    PAYMENT_ORDER_EXPIRATION_BATCH=0 \
    PAYMENT_DISABLE_ORDER_EXPIRATION=false \
    PAYMENT_PLATEGA_RECONCILE_INTERVAL=0s \
    PAYMENT_PLATEGA_RECONCILE_MIN_AGE=0s \
    PAYMENT_PLATEGA_RECONCILE_MISSING_AFTER=0s \
    PAYMENT_PLATEGA_RECONCILE_BATCH=0 \
    PAYMENT_TON_WALLET_SYNC_INTERVAL=0s

# Promo service PostgreSQL and cache settings.
# PROMO_* overrides global POSTGRES_* and SERVICES_* settings.
ENV PROMO_POSTGRES_HOST= \
    PROMO_POSTGRES_PORT=0 \
    PROMO_POSTGRES_USER= \
    PROMO_POSTGRES_PASSWORD= \
    PROMO_POSTGRES_DATABASE= \
    PROMO_MAX_CONNECTIONS=0 \
    PROMO_QUERY_TIMEOUT=0s \
    PROMO_CACHE_L1_DELAY=0s \
    PROMO_CACHE_L2_DELAY=0s \
    PROMO_CACHE_ENABLED=false \
    PROMO_CACHE_SIZE=0 \
    PROMO_CACHE_TTL_CHECK=0s

# Reference service PostgreSQL and cache settings.
# REFERENCE_* overrides global POSTGRES_* and SERVICES_* settings.
ENV REFERENCE_POSTGRES_HOST= \
    REFERENCE_POSTGRES_PORT=0 \
    REFERENCE_POSTGRES_USER= \
    REFERENCE_POSTGRES_PASSWORD= \
    REFERENCE_POSTGRES_DATABASE= \
    REFERENCE_MAX_CONNECTIONS=0 \
    REFERENCE_QUERY_TIMEOUT=0s \
    REFERENCE_CACHE_L1_DELAY=0s \
    REFERENCE_CACHE_L2_DELAY=0s \
    REFERENCE_CACHE_ENABLED=false \
    REFERENCE_CACHE_SIZE=0 \
    REFERENCE_CACHE_TTL_CHECK=0s

# Tasks service PostgreSQL, cache, partner lease and Lua runtime settings.
# TASKS_* overrides global POSTGRES_* and SERVICES_* settings.
ENV TASKS_POSTGRES_HOST= \
    TASKS_POSTGRES_PORT=0 \
    TASKS_POSTGRES_USER= \
    TASKS_POSTGRES_PASSWORD= \
    TASKS_POSTGRES_DATABASE= \
    TASKS_MAX_CONNECTIONS=0 \
    TASKS_QUERY_TIMEOUT=0s \
    TASKS_CACHE_L1_DELAY=0s \
    TASKS_CACHE_L2_DELAY=0s \
    TASKS_CACHE_ENABLED=false \
    TASKS_CACHE_SIZE=0 \
    TASKS_CACHE_TTL_CHECK=0s \
    TASKS_PARTNER_START_LEASE_DURATION=0s \
    TASKS_RUNTIME_ENABLED=false \
    TASKS_RUNTIME_SCRIPT_CACHE_TTL=0s \
    TASKS_RUNTIME_TIMEOUT=0s \
    TASKS_RUNTIME_MAX_MEMORY=0 \
    TASKS_RUNTIME_MAX_HTTP_REQUESTS=0 \
    TASKS_RUNTIME_MAX_RESPONSE_BYTES=0 \
    TASKS_RUNTIME_JSON_BOUNDARY=false \
    TASKS_RUNTIME_STATE_POOL_SIZE=0

COPY --from=build /platform /platform

USER nonroot:nonroot

ENTRYPOINT ["/platform"]
